/**
 * SPDX-License-Identifier: Apache-2.0
 * © Copyright 2023 Hewlett Packard Enterprise Development LP
 * © Copyright 2024 Valentin D'Emmanuele
 */
package gnb

import (
	"fmt"
	"net/netip"

	"github.com/free5gc/ngap/ngapType"
)

type PDUSessionResourceSetupResponseOpts struct {
	AMFUENGAPID int64
	RANUENGAPID int64
	N3GnbIp     netip.Addr
	PDUSessions [16]*PDUSessionInformation
}

func BuildPDUSessionResourceSetupResponse(opts *PDUSessionResourceSetupResponseOpts) (ngapType.NGAPPDU, error) {
	pdu := ngapType.NGAPPDU{}

	pdu.Present = ngapType.NGAPPDUPresentSuccessfulOutcome
	pdu.SuccessfulOutcome = new(ngapType.SuccessfulOutcome)

	successfulOutcome := pdu.SuccessfulOutcome
	successfulOutcome.ProcedureCode.Value = ngapType.ProcedureCodePDUSessionResourceSetup
	successfulOutcome.Criticality.Value = ngapType.CriticalityPresentReject

	successfulOutcome.Value.Present = ngapType.SuccessfulOutcomePresentPDUSessionResourceSetupResponse
	successfulOutcome.Value.PDUSessionResourceSetupResponse = new(ngapType.PDUSessionResourceSetupResponse)

	pDUSessionResourceSetupResponse := successfulOutcome.Value.PDUSessionResourceSetupResponse
	ies := &pDUSessionResourceSetupResponse.ProtocolIEs

	amfIE := ngapType.PDUSessionResourceSetupResponseIEs{}
	amfIE.Id.Value = ngapType.ProtocolIEIDAMFUENGAPID
	amfIE.Criticality.Value = ngapType.CriticalityPresentIgnore
	amfIE.Value.Present = ngapType.PDUSessionResourceSetupResponseIEsPresentAMFUENGAPID
	amfIE.Value.AMFUENGAPID = new(ngapType.AMFUENGAPID)

	aMFUENGAPID := amfIE.Value.AMFUENGAPID
	aMFUENGAPID.Value = opts.AMFUENGAPID

	ies.List = append(ies.List, amfIE)

	ranIE := ngapType.PDUSessionResourceSetupResponseIEs{}
	ranIE.Id.Value = ngapType.ProtocolIEIDRANUENGAPID
	ranIE.Criticality.Value = ngapType.CriticalityPresentIgnore
	ranIE.Value.Present = ngapType.PDUSessionResourceSetupResponseIEsPresentRANUENGAPID
	ranIE.Value.RANUENGAPID = new(ngapType.RANUENGAPID)

	rANUENGAPID := ranIE.Value.RANUENGAPID
	rANUENGAPID.Value = opts.RANUENGAPID

	ies.List = append(ies.List, ranIE)

	setupListIE := ngapType.PDUSessionResourceSetupResponseIEs{}
	setupListIE.Id.Value = ngapType.ProtocolIEIDPDUSessionResourceSetupListSURes
	setupListIE.Criticality.Value = ngapType.CriticalityPresentIgnore
	setupListIE.Value.Present = ngapType.PDUSessionResourceSetupResponseIEsPresentPDUSessionResourceSetupListSURes
	setupListIE.Value.PDUSessionResourceSetupListSURes = new(ngapType.PDUSessionResourceSetupListSURes)

	pDUSessionResourceSetupListSURes := setupListIE.Value.PDUSessionResourceSetupListSURes

	for _, pduSession := range opts.PDUSessions {
		if pduSession == nil {
			continue
		}

		// PDU Session Resource Setup Response Item in PDU Session Resource Setup Response List
		pDUSessionResourceSetupItemSURes := ngapType.PDUSessionResourceSetupItemSURes{}

		// PDU Session ID : This is an unique identifier generated by UE. Can’t be same as any existing PDU session.
		pDUSessionResourceSetupItemSURes.PDUSessionID.Value = pduSession.PDUSessionID

		respTransf, err := GetPDUSessionResourceSetupResponseTransfer(opts.N3GnbIp, pduSession.DLTeid, pduSession.QFI)
		if err != nil {
			return pdu, fmt.Errorf("failed to get PDUSessionResourceSetupResponseTransfer: %v", err)
		}

		pDUSessionResourceSetupItemSURes.PDUSessionResourceSetupResponseTransfer = respTransf

		pDUSessionResourceSetupListSURes.List = append(pDUSessionResourceSetupListSURes.List, pDUSessionResourceSetupItemSURes)
	}

	ies.List = append(ies.List, setupListIE)

	return pdu, nil
}
